
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE1_SOC(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
    
    //////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// PS2 //////////
	inout 		          		PS2_CLK,
	inout 		          		PS2_CLK2,
	inout 		          		PS2_DAT,
	inout 		          		PS2_DAT2
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

wire scan_ready;
wire [7:0] scan_code;

//=======================================================
//  Structural coding
//=======================================================

assign LEDR = scan_code;

ps2_controller keyboard (
    .reset(!KEY[0]),
    .clk(CLOCK_50),
    .ps2_clock(PS2_CLK),
    .ps2_data(PS2_DAT),
    .scan_ready(scan_ready),
    .scan_code(scan_code)
);


endmodule
