
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE1_SOC(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// VGA //////////
	output		     [7:0]		VGA_B,
	output		          		VGA_BLANK_N,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output		          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output		          		VGA_VS
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

wire clk_vga;
wire vga_clk_0, vga_clk_1, vga_clk_2, sys_clk;

//=======================================================
//  Structural coding
//=======================================================

// If it is not required to encode sync
// information onto the ADV7123, the SYNC input should be tied
// to logic low. datasheet p.18
assign VGA_SYNC_N = 1'b0;


assign VGA_CLK = vga_clk_0;
vga_pll vga_pll_inst(
    .refclk(CLOCK_50),
    .rst(!KEY[0]), 
    .outclk_0(vga_clk_0), // 25 MHz
    .outclk_1(vga_clk_1), // 40 MHz
    .outclk_2(vga_clk_2), // 33 MHz
    .outclk_3(sys_clk) // 100 MHz
);

/*
assign VGA_CLK = clk_vga;
clock_25 clk_25 (
    .CLOCK_50(CLOCK_50),
    .CLOCK_25(clk_vga)
);
*/

/*
vga_demo vga_ins(
    .CLOCK_PIXEL(VGA_CLK),
    .RESET(!KEY[0]),
    .VGA_RED(VGA_R),
    .VGA_GREEN(VGA_G),
    .VGA_BLUE(VGA_B),
    .VGA_HS(VGA_HS),
    .VGA_VS(VGA_VS),
    .BLANK_N(VGA_BLANK_N)
);
*/

vga_controller vga_ins(
    .reset(!KEY[0]),
    .sys_clk(sys_clk),
    .vga_clk(VGA_CLK),
    .blank_n(VGA_BLANK_N),
    .HS(VGA_HS),
    .VS(VGA_VS),
    .red(VGA_R),
    .green(VGA_G),
    .blue(VGA_B)
);

endmodule
